name: shared

description: shared module

publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: "3.10.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  # uses-material-design: true

  assets:
    # - .env
    - define.dev.env
    - define.pro.env
    - define.uat.env
