name: Test, Build and Release apk # Flutter for Android

on: push
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.1'
      - run: 
          cd data 
          flutter pub get
      - run: 
          cd domain 
          flutter pub get
      - run: 
          cd initializer 
          flutter pub get
      - run: 
          cd resources 
          flutter pub get
      - run: 
          cd shared 
          flutter pub get
      - run: 
          cd app 
          flutter pub get
      - run: 
          cd app 
          flutter pub get
      - run:
          cd app
          flutter test
      - run:
          cd app
          flutter build apk
   
# on: push
# name: Test, Build and Release apk
# jobs:
#   build:
#     name: Build APK
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - uses: actions/setup-java@v3
#         with:
#           distribution: 'zulu'
#           java-version: "12.x"
#           cache: 'gradle'
#       - uses: subosito/flutter-action@v2
#         with:
#           flutter-version: "3.10.1"
#           channel: 'stable'
#           cache: true
#       - run: flutter pub get
#       - run: flutter test
#       - run: flutter build apk --debug --split-per-abi
#       - name: Create a Release APK
#         uses: ncipollo/release-action@v1
#         with:
#           artifacts: "build/app/outputs/apk/debug/*.apk"
#           token: ${{ secrets.ECOMMERCEARCTOKEN }}
